### ISSUE TITLE
train my-datasets

### ISSUE THREAD

**Issue by CVUsers** [TwentyBN/sense#104]
1: You didn't say how to make your data set (train your own data set). When you make it on the website, many operations are not good. Didn't you make a detailed readme of the data? I would like to talk about some of the problems I encountered

2: I create a new project through the website. At this time, I write the path as / data, which is a feasible path. But after the creation, I report 404, which shows: 127.0.0.1 -- [03 / Feb / 2021 14:59:41] "get / project / / data http / 1.1" 404-

3: a large number of folders are generated: features train / void logreg, etc., but no matter how I click the annotation button inside, no data is generated

4: You should give the folder of the generated data according to the data.

**Comment by cyjouc** [comment]
hi,would you like share the knowlege with me?

**Comment by CVUsers** [comment]
of course！ I have run it successfully～ do you have the Wechat to communicate easily? ------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;cyjouc&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月4日(星期四) 中午11:08
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] train my-datasets (#104)

**Comment by cyjouc** [comment]
hi,my wechat is hicaicaihi

**Comment by corneliusboehm** [comment]
Hi @CVUsers, thanks for your reports! Are the issues already resolved now or do you still face some problems?
During the last few days we have also deployed some improvements to the project setup tool, so we would be happy if you could give it a try again.
Please let us know if you need further assistance or where we could improve our documentation.

**Comment by CVUsers** [comment]
I have solved it, thank you, can you help me to see a new issue ~ there are some doubts------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;corneliusboehm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月5日(星期五) 晚上7:39
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] train my-datasets (#104)

**Comment by kkzh2313** [comment]
![image](https://user-images.githubusercontent.com/34201133/108977906-02593380-76c4-11eb-9b27-f9d20f6430f1.png)
hi, I have a problem. After recording the video, the code appears the problem as shown in the picture, and the recorded video is not generated in the folder. How should I solve it?

**Comment by CVUsers** [comment]
你可以加我微信，我近期会出一期这个的文章和教学------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;kkzh2313&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月24日(星期三) 下午5:19
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] train my-datasets (#104)

**Comment by CVUsers** [comment]
zxx15277368495z------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;kkzh2313&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月24日(星期三) 下午5:19
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] train my-datasets (#104)

**Comment by corneliusboehm** [comment]
Hi @kkzh2313, can you make sure that `ffmpeg` is installed on your system, e.g. by running `ffmpeg -version`? If it is not installed, you can do that (on Linux) with the following commands:
```bash
sudo apt update
sudo apt install ffmpeg
```
Let me know if that works for you!
