### ISSUE TITLE
model fps

### ISSUE THREAD

**Issue by CVUsers** [TwentyBN/sense#108]
Excuse me, I have tested your model and my own training model, and I have some doubts!

1: Whether a CPU device can use mobilenet (not using efficiency net) and achieve normal effect without frame skipped

2: The GPU of your model's efficient net and mobile net can't frame skip. Would you like to know if your camera FPS is simply displayed by opencv? Is your model FPS reasoning speed? I can see by adjusting FPS and step_ Size to change

3: I mainly want to ask about speed optimization. Does your realtime mean camera FPS or? How to optimize our CPU if we want to run in real time? My deployment device is CPU

model fps
 请问一下，我分别测试了您的模型和我自己训练的模型，有了一些些疑惑！
1：一个较若的cpu设备，能否使用mobilenet （不使用efficient net）， 能不能达到正常的效果，不出现Frame skipped.
2:   您模型的efficient net 和mobile net 我这边gpu都不会frame skip ，想请问您的camera fps 是单纯opencv显示的fps吗？ 您的model fps 是推理速度吗？ 我看到可以通过调整fps 和step_size 来改变
3：我主要还是想问速度优化部分，您的realtime 意思是camera fps还是？   我们cpu想跑实时该怎么优化呢？我部署设备是cpu

**Comment by corneliusboehm** [comment]
1. Yes, it is definitely possible to run both our MobileNet and EfficientNet on CPU devices, but you might require a stronger processor.

2./3. On the right hardware, the displayed camera FPS should be around 16 and the model FPS around 4. The difference is due to the model architecture, which consumes multiple frames to output one prediction. Does that answer your questions?

**Comment by CVUsers** [comment]
感谢～，只要一出现frame skip 就说明现在不能实时了是吗？设备就过低，只要不出现，就不影响模型的推理效果吧？  另外，如何提高model fps？总是4，为什么不能到实时的30fps呢？我能修改吗？另外我改efficient 变成mobilenet 显示的model fps已经是4，我改了mobilenet.py的step和fps还是不高，按道理mobilenet比effi快很多呀？，不过精度有些低了------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;corneliusboehm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月5日(星期五) 晚上7:54
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] model fps (#108)

**Comment by CVUsers** [comment]
Thank you. As soon as frame skip appears, it means that it can't be real-time now, right? The equipment is too low, as long as it does not appear, it will not affect the reasoning effect of the model, right? In addition, how to improve model FPS? It's always 4. Why can't we get real-time 30fps? Can I change it? In addition, I changed the efficiency to mobile, and the displayed model FPS is already 4, so I changed it mobilenet.py Step and FPs are still not high. In principle, mobilenet is much faster than EFI? But the accuracy is a little bit low

**Comment by corneliusboehm** [comment]
If a frame skip appears, it just means the model isn't running at perfect speed and predictions might be worse, but it still will always process the most recent frames and don't build up a time delay.
As long as you don't see frame skip messages, everything should be fine.

A model FPS of 4 is the maximum we have specified for this model. For the applications we tested with, this was frequent enough and can still be considered real-time. Increasing the output FPS would require changing the model architecture and add a significant amount of computation. Also you wouldn't be able to use our pre-trained models.

**Comment by CVUsers** [comment]
OK, I see. Thank you ~ Are you still ready to maintain this project? Maybe I can join in and help you. Besides, do you have WeChat? We may be able to communicate more conveniently------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;corneliusboehm&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年2月5日(星期五) 晚上8:36
收件人:&nbsp;&quot;TwentyBN/sense&quot;<sense@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [TwentyBN/sense] model fps (#108)

**Comment by corneliusboehm** [comment]
No WeChat here, sorry :shrug: 

This project is actively being developed by our team at 20bn. You're always welcome to submit pull requests if you have suggestions for improvements :slightly_smiling_face: Also we would be interested in seeing any cool applications that you build with our tech and could highlight those in the project.
