### ISSUE TITLE
  Training 20bn data

### ISSUE THREAD

**Issue by CVUsers** [TwentyBN/sense#109]
Hello, 20bn data has been cut into frames. What should you do with sense? Is there a training course for this? We're doing it

**Comment by florianletsch** [comment]
I understand you want to know how to use sense to train on existing 20bn datasets like [Jester](https://20bn.com/datasets/jester/v1) and [Something-Something](https://20bn.com/datasets/something-something/v2).

Right now, that isn't the purpose of sense. Instead, you can use the pre-trained weights (which are trained on Jester, Something-Something, and millions of additional videos we own internally). 

You can use gesture classification outputs out-of-the-box (check the gesture classification example script).

If you want to transfer-learn to other data, right now you have to provide video files, not frames.
I agree it would be good to also support training from sequences of images. I'll include that in our internal roadmap and will discuss with the team. Thanks for your suggestion.

**Comment by MoonBunnyZZZ** [comment]
> Hello, 20bn data has been cut into frames. What should you do with sense? Is there a training course for this? We're doing it

Hi, do you have the downloaded model ? @CVUsers

**Comment by MoonBunnyZZZ** [comment]
> I understand you want to know how to use sense to train on existing 20bn datasets like [Jester](https://20bn.com/datasets/jester/v1) and [Something-Something](https://20bn.com/datasets/something-something/v2).
> 
> Right now, that isn't the purpose of sense. Instead, you can use the pre-trained weights (which are trained on Jester, Something-Something, and millions of additional videos we own internally).
> 
> You can use gesture classification outputs out-of-the-box (check the gesture classification example script).
> 
> If you want to transfer-learn to other data, right now you have to provide video files, not frames. I agree it would be good to also support training from sequences of images. I'll include that in our internal roadmap and will discuss with the team. Thanks for your suggestion.

Hi, the offical link is not available.Could you share the pre-trained weights? @floriandotpy
