### ISSUE TITLE
Gesture recognition script does not quit on Ctrl+C

### ISSUE THREAD

**Issue by nahuakang** [TwentyBN/sense#11]
Running:
```
(realtimenet) ➜  20bn-realtimenet git:(playground) PYTHONPATH=. python scripts/gesture_recognition.py  
```
and then input `Ctrl+C` in the terminal does not properly quit the program. The following output is displayed:
```
^CTraceback (most recent call last):
  File "scripts/gesture_recognition.py", line 78, in <module>
    path_out)
  File "/home/nahua/projects/20bn/20bn-realtimenet/realtimenet/engine.py", line 97, in run_inference_engine
    img_tuple = framegrabber.get_image()
  File "/home/nahua/projects/20bn/20bn-realtimenet/realtimenet/camera.py", line 63, in get_image
    return self.frames.get()
  File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/queue.py", line 164, in get
    self.not_empty.wait()
  File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
*** Frame skipped ***
^CException ignored in: <module 'threading' from '/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
And the program is terminated on the second input of `Ctrl+C`.

**Comment by MoonBunnyZZZ** [comment]
> Running:
> 
> ```
> (realtimenet) ➜  20bn-realtimenet git:(playground) PYTHONPATH=. python scripts/gesture_recognition.py  
> ```
> 
> and then input `Ctrl+C` in the terminal does not properly quit the program. The following output is displayed:
> 
> ```
> ^CTraceback (most recent call last):
>   File "scripts/gesture_recognition.py", line 78, in <module>
>     path_out)
>   File "/home/nahua/projects/20bn/20bn-realtimenet/realtimenet/engine.py", line 97, in run_inference_engine
>     img_tuple = framegrabber.get_image()
>   File "/home/nahua/projects/20bn/20bn-realtimenet/realtimenet/camera.py", line 63, in get_image
>     return self.frames.get()
>   File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/queue.py", line 164, in get
>     self.not_empty.wait()
>   File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 295, in wait
>     waiter.acquire()
> KeyboardInterrupt
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> *** Frame skipped ***
> ^CException ignored in: <module 'threading' from '/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py'>
> Traceback (most recent call last):
>   File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1294, in _shutdown
>     t.join()
>   File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1056, in join
>     self._wait_for_tstate_lock()
>   File "/home/nahua/anaconda3/envs/realtimenet/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
>     elif lock.acquire(block, timeout):
> KeyboardInterrupt
> ```
> 
> And the program is terminated on the second input of `Ctrl+C`.

Could you share the downloaded model file?
