### ISSUE TITLE
paper

### ISSUE THREAD

**Issue by XiaoJiNu** [TwentyBN/sense#15]
Hi, where can I get your paper?

**Comment by FishEatApple** [comment]
+1

**Comment by guillaumebrg** [comment]
Hi! We don't have a paper yet (work in progress). We have this blogpost though: https://medium.com/twentybn/towards-situated-visual-ai-via-end-to-end-learning-on-video-clips-2832bd9d519f.

**Comment by FishEatApple** [comment]
> Hi! We don't have a paper yet (work in progress). We have this blogpost though: https://medium.com/twentybn/towards-situated-visual-ai-via-end-to-end-learning-on-video-clips-2832bd9d519f.

Thank you !! , but why HTTP ERROR 400 ? The link cannot be opened

**Comment by guillaumebrg** [comment]
> Thank you !! , but why HTTP ERROR 400 ? The link cannot be opened

The link works for me. It is a Medium post. Is Medium accessible where you are?

**Comment by FishEatApple** [comment]
> > Thank you !! , but why HTTP ERROR 400 ? The link cannot be opened
> 
> The link works for me. It is a Medium post. Is Medium accessible where you are?

I can open it now . Thank you , great work !
