### ISSUE TITLE
device

### ISSUE THREAD

**Issue by luhuiwu** [TwentyBN/sense#16]
I have tested it on my computer, but performs is not good. what is wrong?

**Comment by zahidzqj** [comment]
me too

**Comment by guillaumebrg** [comment]
Hi! Thanks for reporting. 
1. Which script have you tried? 
2. What hardware are you trying to run it on? CPU or GPU specs would be useful. 
3. Can you check your terminal and see if get any warning messages while running the script?

**Comment by zahidzqj** [comment]
I run it on CPU, and I got warning messages  *** Unused frames *** when I run 'gesture_recognition.py'. The same result appears in ‘fitness_tracker.py‘, but occasionally you can see the result.

**Comment by guillaumebrg** [comment]
These _*** Unused frames ***_ messages mean that the inference engine thread is too slow and can't process 16 frames per seconds... as a result, some frames are thrown away. This should explain your performance issues (at least partially). Which script were you testing? Do you maybe have a more powerful CPU you can test it on?

**Comment by MoonBunnyZZZ** [comment]
> I have tested it on my computer, but performs is not good. what is wrong?

Could you share the downloaded model file?

**Comment by MoonBunnyZZZ** [comment]
> I run it on CPU, and I got warning messages *** Unused frames *** when I run 'gesture_recognition.py'. The same result appears in ‘fitness_tracker.py‘, but occasionally you can see the result.

Could you share the downloaded model file?
