### ISSUE TITLE
About the pretrain model

### ISSUE THREAD

**Issue by luchen828** [TwentyBN/sense#178]
hi,Can the pre-training model for fitness tracking be provided?

**Comment by guillaumebrg** [comment]
Hi @luchen828, the fitness tracking model should already be provided. Have you followed the README instructions and downloaded the model weights from [here](https://20bn.com/licensing/sdk/evaluation)?

**Comment by luchen828** [comment]
are you sure ?i mean the calorise model

**Comment by luchen828** [comment]
sien_lite_met_converter.ckpt  simn_lite_met_converter.ckpt
sien_met_converter.ckpt       simn_met_converter.ckpt
but the size of sien_met_converter.ckpt is only 514kB, is right?

**Comment by guillaumebrg** [comment]
Yes, that's right. It's small because those files only contain the weights of the calorie "head" network. Weights of lower layers should be in the `backbone` folder.

I think you ran `ls -R` from `resources/calorie_estimation`. Could you do the same from `resources`?

**Comment by luchen828** [comment]
gesture_recognition   fitness_activity_recognition  backbone
fitness_rep_counting  calorie_estimation            action_recognition

**Comment by guillaumebrg** [comment]
What do you have in `resources/backbone`?

**Comment by luchen828** [comment]
strided_inflated_efficientnet.ckpt  strided_inflated_mobilenet.ckpt

**Comment by guillaumebrg** [comment]
Looks good to me. Are you on the latest `master` branch? You might have to `git pull`. 
What does the error look like when you run the calorie estimation script?

**Comment by luchen828** [comment]
when run the calorie estimation script
the error is  " please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old"
it's like the pytorch version you train the model is too high

**Comment by guillaumebrg** [comment]
> it's like the pytorch version you train the model is too high

... or that your local PyTorch version is too old ;)

PyTorch changed its serialization format not so long ago. Can you try to upgrade your PyTorch and run it again?

**Comment by luchen828** [comment]
yes,my torch is 1.4 version.it's to low comparied with 1.7 .thank you very much!

**Comment by JonyJiang123** [comment]
@luchen828  Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ?  The web was broken

**Comment by biel-jony** [comment]
@luchen828  Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ?  The web was broken

**Comment by luchen828** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quic/sense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 中午11:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quic/sense] About the pretrain model (#178)





 
@luchen828  Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ?  The web was broken
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JonyJiang123** [comment]
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quic/sense" ***@***.***&gt;; 发送时间:&nbsp;2021年11月10日(星期三) 中午11:17 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [quic/sense] About the pretrain model (#178) @luchen828 Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ? The web was broken — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

what's this, Bro

**Comment by luchen828** [comment]
模型太大被限制了，发不过去


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "quic/sense"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 中午11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [quic/sense] About the pretrain model (#178)





  
------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quic/sense" @.&gt;; 发送时间:&nbsp;2021年11月10日(星期三) 中午11:17 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quic/sense] About the pretrain model (#178) @luchen828 Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ? The web was broken — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
what's this, Bro
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by JonyJiang123** [comment]
> 模型太大被限制了，发不过去
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quic/sense" ***@***.***&gt;; 发送时间:&nbsp;2021年11月10日(星期三) 中午11:29 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [quic/sense] About the pretrain model (#178)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "quic/sense" @.&gt;; 发送时间:&nbsp;2021年11月10日(星期三) 中午11:17 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [quic/sense] About the pretrain model (#178) @luchen828 Could you share pre-trained weights which downloaded from https://20bn.com/licensing/sdk/evaluation ? The web was broken — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. what's this, Bro — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Could you send it to my email 13576080222@163.com?  or any other ways?

**Comment by MoonBunnyZZZ** [comment]
> yes,my torch is 1.4 version.it's to low comparied with 1.7 .thank you very much!

可以分享一下模型文件吗？比如放到网盘上    @luchen828

**Comment by KeonAcute** [comment]
@luchen828 麻烦能分享一下权重模型的文件吗？我的邮箱17601026331@163.com，非常感谢！

**Comment by Ozone-oo** [comment]
@luchen828 可以分享下backbone权重模型文件？邮箱1871805784@qq.com

**Comment by koralm** [comment]
Anyone can share  pre-trained weights ?

**Comment by Ozone-oo** [comment]
> Anyone can share pre-trained weights ?

https://1drv.ms/u/s!AgK8kNkUacE6mKkHlstyUExsKe6N_A?e=frmHdS
