### ISSUE TITLE
Is the dataset for Action Recognition open source?

### ISSUE THREAD

**Issue by xiaomingnio** [TwentyBN/sense#180]
I see Action Recognition demo has some action not in jester and something, how can I acquire it?

**Comment by xiaomingnio** [comment]
![image](https://user-images.githubusercontent.com/25093691/122195959-626d2300-cec9-11eb-84b5-f136117fbeb3.png)

**Comment by guillaumebrg** [comment]
Hi! That is correct, only a subset of the actions supported in that demo is freely available (via our Jester dataset). The other actions are not publicly available.

**Comment by guillaumebrg** [comment]
Closing this now. Please let me know if you have any other questions.
