### ISSUE TITLE
always shows "doing other things"!

### ISSUE THREAD

**Issue by taotaoyuhust** [TwentyBN/sense#32]
THanks for the model, i downloaded and tested it on my notebook (4 core cpu) using the command 
python run_gesture_recognition.py

But the video always shows the result "doing other things" , i made many gestures such as "thumb up,nodding"
the output prints "*** Frame skipped ***"
Is it means the fps 16 is too high?

**Comment by guillaumebrg** [comment]
Hi! Yes, these "*** Frame skipped ***" messages indicates that the inference engine can't keep up with the amount of frames to process and ends up throwing away some of them. This will affect the recognition accuracy.

**Comment by MoonBunnyZZZ** [comment]
> THanks for the model, i downloaded and tested it on my notebook (4 core cpu) using the command python run_gesture_recognition.py
> 
> But the video always shows the result "doing other things" , i made many gestures such as "thumb up,nodding" the output prints "*** Frame skipped ***" Is it means the fps 16 is too high?

Hello, could you share the downloaded model?
